#!/bin/bash

set -euo pipefail

[[ "$PROCEDUREKIT_HASH" == "change-me" ]] && echo "You need to set \$PROCEDUREKIT_HASH" && exit 1

echo "--- :git: Updating submodule"

echo "cd submodules/ProcedureKit"
cd "submodules/ProcedureKit"

echo "git fetch origin"
git fetch origin

echo "git checkout $PROCEDUREKIT_HASH"
git checkout $PROCEDUREKIT_HASH

echo "cd ../.."
cd "../.."

echo "bundle install --quiet"
bundle install --quiet

echo "--- CocoaPods"
bundle exec pod install

echo "--- Build & Test"

echo "bundle exec xcodebuild -workspace TryProcedureKit.xcworkspace -scheme TryProcedureKit clean build test | xcpretty"
bundle exec xcodebuild -workspace TryProcedureKit.xcworkspace -scheme TryProcedureKit clean build test | xcpretty